name: ci-angular-workflow-dev

# Especifica quando o fluxo de trabalho deve ser executado
on: [pull_request, push]

# Define as etapas que compõem o fluxo de trabalho
jobs:
  # Nome do trabalho
  ci-angular-workflow:
    runs-on: ubuntu-latest
    # Define as etapas que compõem o trabalho
    steps:
      # Clona o repositório com a action já disponível do GitHub Checkout
      - uses: actions/checkout@v3
      # Instala o Node.js
      - name: Using Node.js
        uses: actions/setup-node@v2
        # Passando argumentos para a action
        with:
          node-version: '16.x' # Altere para a versão do Node.js que seu projeto utiliza
      # Rodando a action manualmente
      - name: run install, build and test
        # Rodando os comandos npm install, npm run build e npm run test
        run: |
          npm install
          npm run build
          npm run test
